[proxy]
host = "http://127.0.0.1:8080"

[account]
username = ""
password = ""

[option]
#这里本来应该有，但是现在暂时留空,因为我偷懒了

[prompt]
const_positive_prompt = "1girl,cat_girl,long_hair,blue_eyes,white_hair,blue_dress,animal_ears,cat_ears,cat_tail"
const_negative_prompt = ""
list = [
    'wlop',
    'ask (askzy)',
    'ciloranko',
    'ke-ta',
    'reoen'
]