[proxy]
host = "http://127.0.0.1:7890"

[account]
username = ""
password = ""

[option]
#图像分辨率，必须是以下三个
#832X1216：NORMAL_PORTRAIT
#1216X832：NORMAL_LANDSCAPE
#1024X1024：NORMAL_SQUARE
#如果留空，那么将会在这三个里随机
image_size = ""
#图像种子，为0则随机，否则按照提供的种子生成图像，种子数字必须在1到4294967295之间
seed = 0
#步数，默认28
steps = 28
#采样器，可选采样器：k_euler，k_euler_ancestral，k_dpmpp_2s_ancestral，ddim，k_dpmpp_2m，k_dpmpp_sde，留空则为k_euler
sampler = "k_euler_ancestral"
#是否开启SMEA，True开启，False关闭
SMEA = "True"
#是否开启DYN，True开启，False关闭，开启DYN会自动开SMEA
DYN = "False"
#Prompt Guidance默认5，范围0-10，步进0.1
cfg_scale = 5
#Prompt Guidance Rescale默认0，范围0-1，步进0.02
cfg_rescale = 0

[prompt]
#固定tag，会拼接在画师tag后
const_positive_prompt = "1girl,cat_girl,long_hair,blue_eyes,white_hair,blue_dress,animal_ears,cat_ears,cat_tail"
#负面tag
const_negative_prompt = "lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg artifacts, bad quality, watermark, unfinished, displeasing, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract],{{weibo_username}},female_pubic_hair,{{weibo_logo}},low quality,@_@,chibi,character doll,{{{{{chibi,doll}}}}},inset"
#画师tag，这里的画师tag会被排列组合后用于生成
list = [
    'wlop',
    'ask (askzy)',
    'ciloranko',
    'ke-ta',
    'reoen'
]